export const SEARCH_PENDING = '[SEARCH] SEARCH_PENDING';
export const SEARCH_SUCCESS = '[SEARCH] SEARCH_SUCCESS';
export const SEARCH_ERROR = '[SEARCH] SEARCH_ERROR';
export const CANCEL_SEARCH = '[SEARCH] CANCEL_SEARCH';
export const SEARCH_CANCELED = '[SEARCH_CANCELED] SEARCH_CANCELED';
export const CAN_PERFORM_SEARCH = '[CAN_PERFORM_SEARCH] CAN_PERFORM_SEARCH';
export const SET_QUERY = '[QUERY] SET_QUERY';
